### ISSUE TITLE
Buffer package can't be found

### ISSUE THREAD

**Issue by davidgasquez** [jwinternheimer/mrr_forecaster#6]
Hey there! While trying to execute this cronjob in our Apollo cluster I found that the latest build wasn't working. This is the trace:

```
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in library(buffer) : there is no package called ‘buffer’
Execution halted
```

Not sure what's happening there but though you might have better background here! To reproduce this, the best way would be building the image from the Dockerfile from scratch (`docker build --no-cache -t julheimer/mrr_forecaster:0.1.0 .`).

**Comment by jwinternheimer** [comment]
Heya @davidgasquez! Thanks for creating this issue. 😄 

I built the image from scratch and it seems to run fine, so I'm not sure what's up exactly! 

```
The downloaded source packages are in
	‘/tmp/downloaded_packages’
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘buffer’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (buffer)
 ---> fa5ef61d17a2
Removing intermediate container cc12d5f54d67
Step 3/4 : ADD forecast.R forecast.R
 ---> acff5ca96dfe
Step 4/4 : CMD Rscript forecast.R
 ---> Running in 54a3f5043283
 ---> a6136ac6aae9
Removing intermediate container 54a3f5043283
Successfully built a6136ac6aae9
Successfully tagged julheimer/mrr_forecaster:0.1.0
```
Shouldn't these lines in the Dockerfile download the buffer package if it doesn't exist yet? 

```
RUN install2.r --error \
    -r 'http://cran.rstudio.com' \
    httr \
    forecast \
  && installGithub.r \
    sicarul/redshiftTools \
    jwinternheimer/buffer \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
```

**Comment by davidgasquez** [comment]
Ups! I forgot to mention that the error is when running it locally! :sweat_smile: 

Running `make` with the latest code should give you also the error.

**Comment by jwinternheimer** [comment]
Whoops! My bad, I didn't push my latest changes. Are you still getting the errors after pulling in the latest changes? Maybe we can walk through it together tomorrow 😄
